name: build-camilladsp-alsa-artifact
on: { workflow_dispatch: {} }
permissions: { contents: write }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { ref: master, fetch-depth: 0 }

      - uses: dtolnay/rust-toolchain@stable

      - name: System deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libasound2-dev libssl-dev cmake clang

      - name: Sanity check
        run: |
          rustc -V
          cargo -V
          test -f Cargo.toml || (echo "Manca Cargo.toml" && exit 2)
          ls -la

      - name: Build ALSA-only
        env:
          RUSTFLAGS: "-C target-cpu=x86-64-v2"
          CARGO_TERM_COLOR: always
        run: |
          cargo build --release --no-default-features --features "backend-alsa,websocket"
          strip target/release/camilladsp
          ldd target/release/camilladsp | grep -i pulse && exit 1 || echo "OK no Pulse"

      - name: Pack
        run: |
          mkdir -p dist && cp target/release/camilladsp dist/
          tar -C dist -czf camilladsp-linux-amd64-alsa.tar.gz camilladsp
          sha256sum camilladsp-linux-amd64-alsa.tar.gz > camilladsp-linux-amd64-alsa.tar.gz.sha256

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: camilladsp-linux-amd64-alsa
          path: |
            camilladsp-linux-amd64-alsa.tar.gz
            camilladsp-linux-amd64-alsa.tar.gz.sha256
