name: build-camilladsp-alsa-artifact
on: { workflow_dispatch: {} }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { ref: master, fetch-depth: 0 }

      - uses: dtolnay/rust-toolchain@stable

      - name: Deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libasound2-dev nasm

      - name: Build minimal (stdin/stdout + websocket)
        env: { RUSTFLAGS: "-C target-cpu=x86-64-v2", CARGO_TERM_COLOR: always }
        run: |
          cargo build --release --no-default-features --features websocket
          strip target/release/camilladsp

      - name: Pack
        run: tar -C target/release -czf camilladsp-linux-amd64-alsa.tar.gz camilladsp

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: camilladsp-linux-amd64-alsa
          path: camilladsp-linux-amd64-alsa.tar.gz
